apiVersion: v1
kind: Service
metadata:
  name: niveflix-app
  labels:
    app: niveflix-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: niveflix-app
